spring:
  application:
    name: hortinha
  flyway:
    depends-on: entityManagerFactory
  datasource:
    url: jdbc:postgresql://localhost:5432/hortinha
    username: hortinha_user
    password: hortinha123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true

server:
  port: 8080