spring:
  application:
    name: hortinha
  flyway:
    depends-on: entityManagerFactory
  datasource:
    url: jdbc:postgresql://localhost:5432/hortinha
    username: hortinha_user
    password: hortinha123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true

server:
  port: 8080

security:
  jwt:
    secret-key: 29e173be957eb2e6981cc208b67247ff8f894a632764f65ede6cba377d534663
    expiration-time: 3600000