services:
  postgres:
    image: postgres:15-alpine
    container_name: hortinha-postgres
    environment:
      POSTGRES_DB: hortinha
      POSTGRES_USER: hortinha_user
      POSTGRES_PASSWORD: hortinha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: